# Generated by Django 3.1 on 2021-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(default='prod', max_length=50)),
                ('Description', models.TextField(default='des', max_length=5000)),
                ('image1', models.ImageField(upload_to='static/Product_Images/Business_Cards/')),
                ('image2', models.ImageField(upload_to='static/Product_Images/Business_Cards/')),
                ('image3', models.ImageField(upload_to='static/Product_Images/Business_Cards/')),
            ],
            options={
                'verbose_name': 'Product List',
            },
        ),
    ]
