# Generated by Django 3.1.4 on 2020-12-24 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('digital_Fast', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('digital_Fast_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('offset_HQ', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('offset_HQ_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('description', models.CharField(default='Des', max_length=5000)),
            ],
            options={
                'verbose_name': '1 - Simple business cards price',
            },
        ),
        migrations.CreateModel(
            name='edge_painted_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('US_Standard_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('US_Standard_Size_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('European_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('European_Size_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('Square', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('Square_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '2 - Edge painted business cards price',
            },
        ),
        migrations.CreateModel(
            name='foil_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US_Standard_size', models.CharField(max_length=555)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '3 - Foil business cards price',
            },
        ),
        migrations.CreateModel(
            name='pantone_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US_Standard_Size', models.CharField(max_length=555)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '5 - Pantone business cards price',
            },
        ),
        migrations.CreateModel(
            name='plastic_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('US_Standard_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='US Standard Size Price')),
                ('US_Standard_Size_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='US Standard Size Price Discounted')),
                ('Credit_card_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Credit Card Size Price')),
                ('Credit_card_Size_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Credit Card Size Price Discounted')),
            ],
            options={
                'verbose_name': '6 - Plastic business cards price',
            },
        ),
        migrations.CreateModel(
            name='raised_ink_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US_Standard_Size', models.CharField(max_length=555)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '7 - Raised ink business cards price',
            },
        ),
        migrations.CreateModel(
            name='raised_spot_uv_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US_Standard_size', models.CharField(max_length=555)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '4 - Raised spot UV business cards price',
            },
        ),
    ]
