# Generated by Django 3.1 on 2021-02-24 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('digital_Fast', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('offset_HQ', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Discount', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Template', models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates')),
            ],
            options={
                'verbose_name': '1 - Simple business cards',
            },
        ),
        migrations.CreateModel(
            name='edge_painted_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('US_Standard_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('US_Standard_Size_Template', models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates')),
                ('European_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('European_Size_Template', models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates')),
                ('Square', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Square_Template', models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates')),
                ('Discount', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Template', models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates')),
            ],
            options={
                'verbose_name': '2 - Edge painted business cards',
            },
        ),
        migrations.CreateModel(
            name='Extra_features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50)),
                ('size_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('paper_type', models.CharField(blank=True, max_length=250)),
                ('paper_type_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('second_side_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('second_side_foil_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('second_side_raied_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('traditional_raised_printing_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('plastic_type', models.CharField(blank=True, max_length=250)),
                ('plastic_type_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('raised_ink_colors', models.CharField(blank=True, max_length=250)),
                ('rasied_ink_colors_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': '0 - Extra Feature',
            },
        ),
        migrations.CreateModel(
            name='foil_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US_Standard_size', models.CharField(blank=True, max_length=555)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Template', models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates')),
            ],
            options={
                'verbose_name': '3 - Foil business cards',
            },
        ),
        migrations.CreateModel(
            name='pantone_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US_Standard_Size', models.CharField(blank=True, max_length=555)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Template', models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates')),
            ],
            options={
                'verbose_name': '5 - Pantone business cards',
            },
        ),
        migrations.CreateModel(
            name='plastic_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('US_Standard_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='US Standard Size Price')),
                ('Credit_card_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Credit Card Size Price')),
                ('Discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Template', models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates')),
            ],
            options={
                'verbose_name': '6 - Plastic business cards',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(default='prod', max_length=50)),
                ('Description', models.TextField(default='des', max_length=5000)),
                ('image1', models.ImageField(upload_to='static/Product_Images/Business_Cards/')),
                ('image2', models.ImageField(upload_to='static/Product_Images/Business_Cards/')),
                ('image3', models.ImageField(upload_to='static/Product_Images/Business_Cards/')),
            ],
            options={
                'verbose_name': 'Product List',
            },
        ),
        migrations.CreateModel(
            name='raised_ink_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('US_Standard_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Template', models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates')),
            ],
            options={
                'verbose_name': '7 - Raised ink business cards',
            },
        ),
        migrations.CreateModel(
            name='raised_spot_uv_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US_Standard_size', models.CharField(blank=True, max_length=555)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Discount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Template', models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates')),
            ],
            options={
                'verbose_name': '4 - Raised spot UV business cards',
            },
        ),
    ]
