# Generated by Django 3.1.4 on 2020-12-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_cards_price',
            name='description',
        ),
        migrations.AddField(
            model_name='business_cards_price',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
        migrations.AddField(
            model_name='edge_painted_business_cards_price',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
        migrations.AddField(
            model_name='foil_business_cards_price',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
        migrations.AddField(
            model_name='pantone_business_cards_price',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
        migrations.AddField(
            model_name='plastic_business_cards_price',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
        migrations.AddField(
            model_name='raised_ink_business_cards_price',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
        migrations.AddField(
            model_name='raised_spot_uv_business_cards_price',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
    ]
