# Generated by Django 3.1 on 2021-02-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0002_auto_20210224_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_cards_price',
            name='Template_ref',
        ),
        migrations.AddField(
            model_name='business_cards_price',
            name='Template',
            field=models.FileField(default='', upload_to='static/templates'),
        ),
    ]
