# Generated by Django 3.1.4 on 2020-12-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0003_business_cards_price_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_cards_price',
            name='Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
    ]
