# Generated by Django 3.1 on 2021-02-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0003_auto_20210224_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_cards_price',
            name='Template',
        ),
        migrations.AddField(
            model_name='business_cards_price',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
