# Generated by Django 3.1 on 2021-02-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0004_auto_20210224_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge_painted_business_cards_price',
            name='Template',
        ),
        migrations.RemoveField(
            model_name='foil_business_cards_price',
            name='Template',
        ),
        migrations.RemoveField(
            model_name='pantone_business_cards_price',
            name='Template',
        ),
        migrations.RemoveField(
            model_name='plastic_business_cards_price',
            name='Template',
        ),
        migrations.RemoveField(
            model_name='raised_ink_business_cards_price',
            name='Template',
        ),
        migrations.RemoveField(
            model_name='raised_spot_uv_business_cards_price',
            name='Template',
        ),
        migrations.AddField(
            model_name='edge_painted_business_cards_price',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='foil_business_cards_price',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='pantone_business_cards_price',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='plastic_business_cards_price',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='raised_ink_business_cards_price',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='raised_spot_uv_business_cards_price',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
