# Generated by Django 3.1.4 on 2020-12-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0004_auto_20201224_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_cards_price',
            old_name='Template',
            new_name='Digital_Fast_Template',
        ),
        migrations.AddField(
            model_name='business_cards_price',
            name='Offset_HQ_Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
    ]
