# Generated by Django 3.1.4 on 2020-12-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0005_auto_20201224_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge_painted_business_cards_price',
            name='European_Size_Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AddField(
            model_name='edge_painted_business_cards_price',
            name='Square_Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AddField(
            model_name='edge_painted_business_cards_price',
            name='US_Standard_Size_Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AddField(
            model_name='pantone_business_cards_price',
            name='Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AddField(
            model_name='plastic_business_cards_price',
            name='Credit_card_Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AddField(
            model_name='plastic_business_cards_price',
            name='US_Standard_Size_Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AddField(
            model_name='raised_ink_business_cards_price',
            name='Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
    ]
