# Generated by Django 3.1.4 on 2020-12-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0006_auto_20201224_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(default='prod', max_length=50)),
                ('Description', models.TextField(default='des', max_length=5000)),
                ('image1', models.ImageField(upload_to='static/Product_Images/Business_Cards/')),
                ('image2', models.ImageField(upload_to='static/Product_Images/Business_Cards/')),
                ('image3', models.ImageField(upload_to='static/Product_Images/Business_Cards/')),
            ],
            options={
                'verbose_name': '0 - Product List',
            },
        ),
        migrations.RemoveField(
            model_name='business_cards_price',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='edge_painted_business_cards_price',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='foil_business_cards_price',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='pantone_business_cards_price',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='plastic_business_cards_price',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='raised_ink_business_cards_price',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='raised_spot_uv_business_cards_price',
            name='Description',
        ),
    ]
