# Generated by Django 3.1.4 on 2021-01-02 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0007_auto_20201225_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_cards_price',
            name='digital_Fast_Discounted',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='business_cards_price',
            name='offset_HQ_Discounted',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
