# Generated by Django 3.1.4 on 2021-01-02 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0009_auto_20210102_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50)),
                ('size_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('paper_type', models.CharField(blank=True, max_length=250)),
                ('paper_type_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('second_side_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('second_side_foil_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('second_side_raied_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('traditional_raised_printing_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('plastic_type', models.CharField(blank=True, max_length=250)),
                ('plastic_type_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('raised_ink_colors', models.CharField(blank=True, max_length=250)),
                ('rasied_ink_colors_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '0.0 Extra Features',
            },
        ),
        migrations.AlterField(
            model_name='pantone_business_cards_price',
            name='US_Standard_Size',
            field=models.CharField(blank=True, max_length=555),
        ),
    ]
