# Generated by Django 3.1.4 on 2021-01-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0010_auto_20210102_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra_features',
            options={'verbose_name': '0 Extra Feature'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product List'},
        ),
    ]
