# Generated by Django 3.1.4 on 2021-01-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0011_auto_20210102_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra_features',
            options={'verbose_name': '0 - Extra Feature'},
        ),
    ]
