# Generated by Django 3.1.4 on 2021-01-08 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0012_auto_20210102_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_cards_price',
            name='Digital_Fast_Template',
        ),
        migrations.RemoveField(
            model_name='business_cards_price',
            name='Offset_HQ_Template',
        ),
        migrations.AlterField(
            model_name='business_cards_price',
            name='digital_Fast',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='business_cards_price',
            name='offset_HQ',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='edge_painted_business_cards_price',
            name='European_Size',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='edge_painted_business_cards_price',
            name='European_Size_Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='edge_painted_business_cards_price',
            name='European_Size_Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AlterField(
            model_name='edge_painted_business_cards_price',
            name='Square',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='edge_painted_business_cards_price',
            name='Square_Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='edge_painted_business_cards_price',
            name='Square_Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AlterField(
            model_name='edge_painted_business_cards_price',
            name='US_Standard_Size',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='edge_painted_business_cards_price',
            name='US_Standard_Size_Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='edge_painted_business_cards_price',
            name='US_Standard_Size_Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AlterField(
            model_name='extra_features',
            name='paper_type_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='extra_features',
            name='plastic_type_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='extra_features',
            name='rasied_ink_colors_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='extra_features',
            name='second_side_foil_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='extra_features',
            name='second_side_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='extra_features',
            name='second_side_raied_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='extra_features',
            name='size_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='extra_features',
            name='traditional_raised_printing_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='foil_business_cards_price',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='foil_business_cards_price',
            name='price_Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='pantone_business_cards_price',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AlterField(
            model_name='pantone_business_cards_price',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='pantone_business_cards_price',
            name='price_Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='plastic_business_cards_price',
            name='Credit_card_Size',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Credit Card Size Price'),
        ),
        migrations.AlterField(
            model_name='plastic_business_cards_price',
            name='Credit_card_Size_Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Credit Card Size Price Discounted'),
        ),
        migrations.AlterField(
            model_name='plastic_business_cards_price',
            name='Credit_card_Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AlterField(
            model_name='plastic_business_cards_price',
            name='US_Standard_Size',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='US Standard Size Price'),
        ),
        migrations.AlterField(
            model_name='plastic_business_cards_price',
            name='US_Standard_Size_Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='US Standard Size Price Discounted'),
        ),
        migrations.AlterField(
            model_name='plastic_business_cards_price',
            name='US_Standard_Size_Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AlterField(
            model_name='raised_ink_business_cards_price',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AlterField(
            model_name='raised_ink_business_cards_price',
            name='US_Standard_Size',
            field=models.CharField(blank=True, max_length=555),
        ),
        migrations.AlterField(
            model_name='raised_ink_business_cards_price',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='raised_ink_business_cards_price',
            name='price_Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='raised_spot_uv_business_cards_price',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='raised_spot_uv_business_cards_price',
            name='price_Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
