# Generated by Django 3.1.4 on 2021-01-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0013_auto_20210108_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business_cards_price',
            old_name='digital_Fast_Discounted',
            new_name='Discount',
        ),
        migrations.RemoveField(
            model_name='business_cards_price',
            name='offset_HQ_Discounted',
        ),
    ]
