# Generated by Django 3.1.4 on 2021-01-15 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0014_auto_20210115_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge_painted_business_cards_price',
            name='European_Size_Discounted',
        ),
        migrations.RemoveField(
            model_name='edge_painted_business_cards_price',
            name='Square_Discounted',
        ),
        migrations.RemoveField(
            model_name='edge_painted_business_cards_price',
            name='US_Standard_Size_Discounted',
        ),
        migrations.AddField(
            model_name='edge_painted_business_cards_price',
            name='Discount',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
