# Generated by Django 3.1.4 on 2021-01-21 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0015_auto_20210115_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business_cards_price',
            options={'verbose_name': '1 - Simple business cards'},
        ),
        migrations.AlterModelOptions(
            name='edge_painted_business_cards_price',
            options={'verbose_name': '2 - Edge painted business cards'},
        ),
        migrations.AlterModelOptions(
            name='foil_business_cards_price',
            options={'verbose_name': '3 - Foil business cards'},
        ),
        migrations.AlterModelOptions(
            name='pantone_business_cards_price',
            options={'verbose_name': '5 - Pantone business cards'},
        ),
        migrations.AlterModelOptions(
            name='plastic_business_cards_price',
            options={'verbose_name': '6 - Plastic business cards'},
        ),
        migrations.AlterModelOptions(
            name='raised_ink_business_cards_price',
            options={'verbose_name': '7 - Raised ink business cards'},
        ),
        migrations.AlterModelOptions(
            name='raised_spot_uv_business_cards_price',
            options={'verbose_name': '4 - Raised spot UV business cards'},
        ),
        migrations.RenameField(
            model_name='foil_business_cards_price',
            old_name='price_Discounted',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='pantone_business_cards_price',
            old_name='price_Discounted',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='plastic_business_cards_price',
            old_name='Credit_card_Template',
            new_name='Template',
        ),
        migrations.RenameField(
            model_name='raised_ink_business_cards_price',
            old_name='price_Discounted',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='raised_spot_uv_business_cards_price',
            old_name='price_Discounted',
            new_name='Discount',
        ),
        migrations.RemoveField(
            model_name='plastic_business_cards_price',
            name='Credit_card_Size_Discounted',
        ),
        migrations.RemoveField(
            model_name='plastic_business_cards_price',
            name='US_Standard_Size_Discounted',
        ),
        migrations.RemoveField(
            model_name='plastic_business_cards_price',
            name='US_Standard_Size_Template',
        ),
        migrations.AddField(
            model_name='business_cards_price',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AddField(
            model_name='edge_painted_business_cards_price',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AddField(
            model_name='foil_business_cards_price',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
        migrations.AddField(
            model_name='plastic_business_cards_price',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='raised_spot_uv_business_cards_price',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Cards_Templates'),
        ),
    ]
