# Generated by Django 3.1.4 on 2021-01-21 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0016_auto_20210121_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raised_ink_business_cards_price',
            name='price',
        ),
        migrations.AlterField(
            model_name='raised_ink_business_cards_price',
            name='US_Standard_Size',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
