# Generated by Django 3.1 on 2021-02-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Cards', '0017_auto_20210121_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foil_business_cards_price',
            name='US_Standard_size',
            field=models.CharField(blank=True, max_length=555),
        ),
    ]
