# Generated by Django 3.1.4 on 2021-01-20 12:43

import core.validators
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.CharField(max_length=256)),
                ('Product_name', models.CharField(default='pd', max_length=512)),
                ('Customer', models.CharField(max_length=512)),
                ('Country', models.CharField(default='Co', max_length=512)),
                ('Region', models.CharField(default='R', max_length=512)),
                ('City', models.CharField(default='Ci', max_length=512)),
                ('Zip_Code', models.PositiveIntegerField()),
                ('Delivery_address', models.CharField(default='pd', max_length=1000)),
                ('Mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Email', models.EmailField(max_length=254)),
                ('Delivery_date', models.DateField()),
                ('Status', models.CharField(max_length=256)),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('Size', models.CharField(max_length=1024)),
                ('Price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('Template', models.FileField(max_length=256, upload_to='static/Order_templates', validators=[core.validators.validate_file_extension])),
                ('Second_Template', models.FileField(blank=True, max_length=256, upload_to='static/Order_templates', validators=[core.validators.validate_file_extension])),
                ('Special_requests', models.CharField(blank=True, max_length=5000)),
                ('Extra_features', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': '1 - Orders Table',
                'verbose_name_plural': '1 - Orders Table',
            },
        ),
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024)),
                ('Email', models.EmailField(max_length=254)),
                ('Cell', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Address', models.CharField(max_length=2048)),
                ('Orders', models.ManyToManyField(to='core.Orders')),
            ],
            options={
                'verbose_name': '2 - Customer Information',
                'verbose_name_plural': '2 - Customer Information',
            },
        ),
    ]
