# Generated by Django 3.1.4 on 2020-12-17 18:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('digital_fast', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('digital_fast_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('offset_hq', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('offset_hq_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '1 - Simple business cards price',
            },
        ),
        migrations.CreateModel(
            name='edge_painted_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('US_Standard_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('US_Standard_Size_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('European_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('European_Size_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('Square', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('Square_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '2 - Edge painted business cards price',
            },
        ),
        migrations.CreateModel(
            name='foil_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US_Standard_size', models.CharField(max_length=555)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '3 - Foil business cards price',
            },
        ),
        migrations.CreateModel(
            name='pantone_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=555)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '5 - Pantone business cards price',
            },
        ),
        migrations.CreateModel(
            name='plastic_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('US_Standard_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('US_Standard_Size_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('Credit_card_Size', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('Credit_card_Size_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '6 - Plastic business cards price',
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='raised_ink_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US_Standard_Size', models.CharField(max_length=555)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '7 - Raised ink business cards price',
            },
        ),
        migrations.CreateModel(
            name='raised_spot_uv_business_cards_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US_Standard_size', models.CharField(max_length=555)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '4 - Raised spot UV business cards price',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=2)),
                ('price_dis', models.IntegerField(default=2)),
                ('dimensionX', models.IntegerField(default=2)),
                ('dimensionY', models.IntegerField(default=2)),
                ('Quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quantity', to='core.quantity')),
            ],
        ),
    ]
