# Generated by Django 3.1.4 on 2021-01-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_orders_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Country',
            field=models.CharField(default='Co', max_length=512),
        ),
    ]
