# Generated by Django 3.1.4 on 2020-12-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201217_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brochuresandflyers',
            options={'verbose_name': '9 - Brochures and Flyers'},
        ),
        migrations.AlterModelOptions(
            name='calendars',
            options={'verbose_name': '8 - Calendars'},
        ),
    ]
