# Generated by Django 3.1.4 on 2021-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orders_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='City',
            field=models.CharField(default='Ci', max_length=512),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='Country',
            field=models.CharField(default='Co', max_length=512),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='Region',
            field=models.CharField(default='R', max_length=512),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='Zip_Code',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
