# Generated by Django 3.1.4 on 2020-12-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201217_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmailpostcards',
            options={'verbose_name': '11 - Direct Mail PostCards'},
        ),
        migrations.AlterModelOptions(
            name='postcards',
            options={'verbose_name': '10 - Post Cards'},
        ),
        migrations.AlterModelOptions(
            name='quotationdirectmailpostcards',
            options={'verbose_name': '11.1 - Direct Mail PostCards'},
        ),
        migrations.AlterModelOptions(
            name='quotationpostcards',
            options={'verbose_name': '10.1 - Quotation Post Cards'},
        ),
    ]
