# Generated by Django 3.1.4 on 2021-01-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210120_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Address',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
