# Generated by Django 3.1.4 on 2020-12-20 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201220_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('ThreeByFiveByOneByFive', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('ThreeByFiveByOneByFiveDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('TwoByFiveByTwoByFive', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('TwoByFiveByTwoByFiveDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('TwoBySix', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('TwoBySixDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '12 - Hang Tags',
            },
        ),
    ]
