# Generated by Django 3.1.4 on 2021-01-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orders_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Address',
        ),
    ]
