# Generated by Django 3.1.4 on 2020-12-20 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hangtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomHolidayCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('FoldingCard', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Folding card - closed size is 5" x 7"')),
                ('FoldingCardDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Folding card - closed size is 5" x 7" Discounted')),
            ],
            options={
                'verbose_name': '16 - Custom Holiday Cards',
            },
        ),
        migrations.CreateModel(
            name='LabelsAndStickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('TwoByTwo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='2" x 2"')),
                ('TwoByTwoDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='2" x 2" Discounted')),
                ('ThreeByThree', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='3" x 3"')),
                ('ThreeByThreeDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='3" x 3" Discounted')),
                ('FourByFour', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='4" x 4"')),
                ('FourbyFourDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='4" x 4" Discounted')),
            ],
            options={
                'verbose_name': '13 - Labels And Stickers',
            },
        ),
        migrations.CreateModel(
            name='NCRForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('FiveByFiveByEightByFive', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='5.5" x 8.5"')),
                ('FiveByFiveByEightByFiveDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='5.5" x 8.5" Discounted')),
                ('EightByFiveByEleven', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='8.5" x 11"')),
                ('EightByFiveByElevenDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='8.5" x 11" Discounted')),
            ],
            options={
                'verbose_name': '14 - NCR Forms',
            },
        ),
        migrations.CreateModel(
            name='PresentationFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('NineByTwelveFast', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='9" x 12" Fast - Digital Fast')),
                ('NineByTwelveFastDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='9" x 12" Digital Fast Discounted')),
                ('NineByTwelveOffset', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='9" x 12" Offset Folders')),
                ('NinebyTwelveOffsetDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='9" x 12" Offset Discounted')),
            ],
            options={
                'verbose_name': '15 - Presentation Folders',
            },
        ),
        migrations.AlterField(
            model_name='hangtags',
            name='ThreeByFiveByOneByFive',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='3.5" x 1.5"'),
        ),
        migrations.AlterField(
            model_name='hangtags',
            name='ThreeByFiveByOneByFiveDis',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='3.5" x 1.5" Discounted'),
        ),
        migrations.AlterField(
            model_name='hangtags',
            name='TwoByFiveByTwoByFive',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='2.5" x 2.5"'),
        ),
        migrations.AlterField(
            model_name='hangtags',
            name='TwoByFiveByTwoByFiveDis',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='2.5" x 2.5" Discounted'),
        ),
        migrations.AlterField(
            model_name='hangtags',
            name='TwoBySix',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='2" x 6"'),
        ),
        migrations.AlterField(
            model_name='hangtags',
            name='TwoBySixDis',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='2" x 6" Discounted'),
        ),
    ]
