# Generated by Django 3.1.4 on 2020-12-20 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201220_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envelopes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Number10', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='#10 (9.5x4.125)')),
                ('Number10Dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='#10 (9.5x4.125) Discounted')),
                ('NineByTwleve', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='9 x 12')),
                ('NineByTwleveDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='9 x 12 Discounted')),
                ('A7', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='A7 (5.25X7.25)')),
                ('A7Dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='A7 (5.25X7.25) Discounted')),
            ],
            options={
                'verbose_name': '17 - Envelopes',
            },
        ),
        migrations.CreateModel(
            name='FoamcorePosters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': '20 - Foamcore Posters',
            },
        ),
        migrations.CreateModel(
            name='LetterHeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('EightByFiveByEleven', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='8.5" x 11"')),
                ('EightByFiveByElevenDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='8.5" x 11" Discounted')),
            ],
            options={
                'verbose_name': '18 - LetterHeads',
            },
        ),
        migrations.CreateModel(
            name='NotePads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('ThreeBySixByFourByEight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='3.625" x 4.875"')),
                ('ThreeBySixByFourByEightDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='3.625" x 4.875" Discounted')),
            ],
            options={
                'verbose_name': '19 - NotePads',
            },
        ),
        migrations.CreateModel(
            name='QuotationFoamcorePosters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dimensionX', models.PositiveIntegerField(default=0)),
                ('dimensionY', models.PositiveIntegerField(default=0)),
                ('FoamcorePosters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.foamcoreposters', verbose_name='Foamcore Posters')),
            ],
            options={
                'verbose_name': '11.1 - Foamcore Posters',
            },
        ),
    ]
