# Generated by Django 3.1.4 on 2021-01-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_orders_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Delivery_date',
            field=models.DateField(null=True),
        ),
    ]
