# Generated by Django 3.1.4 on 2020-12-20 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_envelopes_foamcoreposters_letterheads_notepads_quotationfoamcoreposters'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterPrinting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': '21 - Poster Printing',
            },
        ),
        migrations.CreateModel(
            name='RetractableBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityFrom', models.PositiveIntegerField(default=0)),
                ('QuantityTo', models.PositiveIntegerField(default=0)),
                ('ThirtyThreeByEighty', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='33" x 80"')),
                ('ThirtyThreeByEightyDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='33" x 80" Discounted')),
            ],
            options={
                'verbose_name': '22 - Retractable Banners',
            },
        ),
        migrations.CreateModel(
            name='TableCovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityFrom', models.PositiveIntegerField(default=0)),
                ('QuantityTo', models.PositiveIntegerField(default=0)),
                ('NinetyByOneThreeTwo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='6 foot table cover (90" x 132")')),
                ('NinetyByOneThreeTwoDis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='6 foot table cover (90" x 132") Discounted')),
            ],
            options={
                'verbose_name': '23 - Table Covers',
            },
        ),
        migrations.AlterModelOptions(
            name='quotationfoamcoreposters',
            options={'verbose_name': '20.1 - Foamcore Posters'},
        ),
        migrations.CreateModel(
            name='QuotationPosterPrinting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dimensionX', models.PositiveIntegerField(default=0)),
                ('dimensionY', models.PositiveIntegerField(default=0)),
                ('PosterPrinting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.posterprinting', verbose_name='Poster Printing')),
            ],
            options={
                'verbose_name': '21.1 - Poster Printing',
            },
        ),
    ]
