# Generated by Django 3.1.4 on 2020-12-20 15:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201220_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorStickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': '26 - Poster Printing',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.CharField(max_length=256)),
                ('Customer', models.CharField(max_length=512)),
                ('Status', models.CharField(max_length=256)),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('Size', models.CharField(max_length=1024)),
                ('Price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '24 - Orders Table',
            },
        ),
        migrations.CreateModel(
            name='QuotationFloorStickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_dis', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dimensionX', models.PositiveIntegerField(default=0)),
                ('dimensionY', models.PositiveIntegerField(default=0)),
                ('FloorStickers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.floorstickers', verbose_name='Poster Printing')),
            ],
            options={
                'verbose_name': '26.1 - Floor Stickers',
            },
        ),
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024)),
                ('Email', models.CharField(max_length=1024)),
                ('Cell', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=2048)),
                ('Orders', models.ManyToManyField(to='core.Orders')),
            ],
            options={
                'verbose_name': '25 - Customer Information',
            },
        ),
    ]
