# Generated by Django 3.1.4 on 2020-12-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customerdata_floorstickers_orders_quotationfloorstickers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business_cards_price',
            options={'verbose_name': '1 - Simple business cards'},
        ),
        migrations.RenameField(
            model_name='business_cards_price',
            old_name='digital_fast',
            new_name='digital_Fast',
        ),
        migrations.RenameField(
            model_name='business_cards_price',
            old_name='digital_fast_dis',
            new_name='digital_Fast_Discounted',
        ),
        migrations.RenameField(
            model_name='business_cards_price',
            old_name='offset_hq',
            new_name='offset_HQ',
        ),
        migrations.RenameField(
            model_name='business_cards_price',
            old_name='offset_hq_dis',
            new_name='offset_HQ_Discounted',
        ),
    ]
