# Generated by Django 3.1.4 on 2020-12-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201220_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge_painted_business_cards_price',
            old_name='European_Size_dis',
            new_name='European_Size_Discounted',
        ),
        migrations.RenameField(
            model_name='edge_painted_business_cards_price',
            old_name='Square_dis',
            new_name='Square_Discounted',
        ),
        migrations.RenameField(
            model_name='edge_painted_business_cards_price',
            old_name='US_Standard_Size_dis',
            new_name='US_Standard_Size_Discounted',
        ),
    ]
