# Generated by Django 3.1.4 on 2021-01-21 13:04

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210121_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Order_templates', validators=[core.validators.validate_file_extension]),
        ),
    ]
