# Generated by Django 3.1.4 on 2021-01-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210121_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=1000)),
                ('Message', models.CharField(max_length=5000)),
                ('Name', models.CharField(max_length=1024)),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': '3 Clientle queries',
                'verbose_name_plural': '3 Clientle queries',
            },
        ),
    ]
