# Generated by Django 3.1.4 on 2020-12-20 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201220_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorstickers',
            options={'verbose_name': '26 - Floor Stickers'},
        ),
        migrations.AlterField(
            model_name='plastic_business_cards_price',
            name='Credit_card_Size',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Credit Card Size Price'),
        ),
        migrations.AlterField(
            model_name='plastic_business_cards_price',
            name='Credit_card_Size_Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Credit Card Size Price Discounted'),
        ),
        migrations.AlterField(
            model_name='plastic_business_cards_price',
            name='US_Standard_Size',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='US Standard Size Price'),
        ),
        migrations.AlterField(
            model_name='plastic_business_cards_price',
            name='US_Standard_Size_Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='US Standard Size Price Discounted'),
        ),
        migrations.AlterField(
            model_name='quotationfloorstickers',
            name='FloorStickers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.floorstickers', verbose_name='Floor Stickers'),
        ),
    ]
