# Generated by Django 3.1.4 on 2020-12-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201220_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brochuresandflyers',
            options={'verbose_name': '9 - Brochures and Flyer'},
        ),
        migrations.AlterModelOptions(
            name='calendars',
            options={'verbose_name': '8 - Calendar'},
        ),
        migrations.AlterModelOptions(
            name='customerdata',
            options={'verbose_name': '25 - Customer Information', 'verbose_name_plural': '25 - Customer Information'},
        ),
        migrations.AlterModelOptions(
            name='customholidaycards',
            options={'verbose_name': '16 - Custom Holiday Card'},
        ),
        migrations.AlterModelOptions(
            name='directmailpostcards',
            options={'verbose_name': '11 - Direct Mail PostCard'},
        ),
        migrations.AlterModelOptions(
            name='envelopes',
            options={'verbose_name': '17 - Envelope'},
        ),
        migrations.AlterModelOptions(
            name='floorstickers',
            options={'verbose_name': '26 - Floor Sticker'},
        ),
        migrations.AlterModelOptions(
            name='foamcoreposters',
            options={'verbose_name': '20 - Foamcore Poster'},
        ),
        migrations.AlterModelOptions(
            name='hangtags',
            options={'verbose_name': '12 - Hang Tag'},
        ),
        migrations.AlterModelOptions(
            name='labelsandstickers',
            options={'verbose_name': '13 - Labels And Sticker'},
        ),
        migrations.AlterModelOptions(
            name='letterheads',
            options={'verbose_name': '18 - LetterHead'},
        ),
        migrations.AlterModelOptions(
            name='ncrforms',
            options={'verbose_name': '14 - NCR Form'},
        ),
        migrations.AlterModelOptions(
            name='notepads',
            options={'verbose_name': '19 - NotePad'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': '24 - Orders Table', 'verbose_name_plural': '24 - Orders Table'},
        ),
        migrations.AlterModelOptions(
            name='postcards',
            options={'verbose_name': '10 - Post Card'},
        ),
        migrations.AlterModelOptions(
            name='presentationfolders',
            options={'verbose_name': '15 - Presentation Folder'},
        ),
        migrations.AlterModelOptions(
            name='quotationdirectmailpostcards',
            options={'verbose_name': '11.1 - Direct Mail PostCard'},
        ),
        migrations.AlterModelOptions(
            name='quotationfloorstickers',
            options={'verbose_name': '26.1 - Floor Sticker'},
        ),
        migrations.AlterModelOptions(
            name='quotationfoamcoreposters',
            options={'verbose_name': '20.1 - Foamcore Poster'},
        ),
        migrations.AlterModelOptions(
            name='quotationpostcards',
            options={'verbose_name': '10.1 - Quotation Post Card'},
        ),
        migrations.AlterModelOptions(
            name='retractablebanners',
            options={'verbose_name': '22 - Retractable Banner'},
        ),
        migrations.AlterModelOptions(
            name='tablecovers',
            options={'verbose_name': '23 - Table Cover'},
        ),
    ]
