# Generated by Django 3.1.4 on 2021-01-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210122_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='Contacted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
