# Generated by Django 3.1.4 on 2021-01-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_messages_contacted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': '3 - Clientle queries', 'verbose_name_plural': '3 - Clientle queries'},
        ),
    ]
