# Generated by Django 3.1.4 on 2020-12-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201220_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_cards_price',
            name='description',
            field=models.CharField(default='Des', max_length=5000),
        ),
    ]
