# Generated by Django 3.1 on 2021-01-30 14:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210125_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': '3 Clientle queries', 'verbose_name_plural': '3 Clientle queries'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='Mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
