# Generated by Django 3.1 on 2021-01-30 13:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210125_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookedcalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Cell', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
                ('Description', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': '4 - Clients Booked calls',
                'verbose_name_plural': '4 - Clients Booked calls',
            },
        ),
        migrations.AlterField(
            model_name='orders',
            name='Mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
