# Generated by Django 3.1 on 2021-01-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210130_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedcalls',
            options={'verbose_name': '4 - Clients Booked call', 'verbose_name_plural': '4 - Clients Booked call'},
        ),
    ]
