# Generated by Django 3.1.4 on 2020-12-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201224_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdata',
            options={'verbose_name': '2 - Customer Information', 'verbose_name_plural': '2 - Customer Information'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': '1 - Orders Table', 'verbose_name_plural': '1 - Orders Table'},
        ),
    ]
