# Generated by Django 3.1 on 2021-02-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210130_1430'),
        ('core', '0017_auto_20210130_1439'),
    ]

    operations = [
    ]
