# Generated by Django 3.1 on 2021-02-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210130_1439'),
        ('core', '0016_auto_20210130_1430'),
    ]

    operations = [
    ]
