# Generated by Django 3.1.4 on 2020-12-24 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201224_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Contact',
            field=models.CharField(default='pd', max_length=512),
        ),
        migrations.AddField(
            model_name='orders',
            name='Delivery_address',
            field=models.CharField(default='pd', max_length=512),
        ),
        migrations.AddField(
            model_name='orders',
            name='Email',
            field=models.EmailField(default=datetime.datetime(2020, 12, 24, 17, 50, 29, 640162, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
