# Generated by Django 3.1 on 2021-02-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20210201_0817'),
        ('core', '0018_merge_20210201_1054'),
    ]

    operations = [
    ]
