# Generated by Django 3.1 on 2021-02-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20210201_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': '3 - Clientle queries', 'verbose_name_plural': '3 - Clientle queries'},
        ),
    ]
