# Generated by Django 3.1.4 on 2021-01-08 16:01

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201224_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Template',
            field=models.FileField(max_length=256, upload_to='static/Order_templates', validators=[core.validators.validate_file_extension]),
        ),
    ]
