# Generated by Django 3.1.4 on 2021-01-19 08:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210108_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Extra_features',
            field=models.JSONField(default='NA'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Second_Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Order_templates', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='orders',
            name='Special_requests',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
