# Generated by Django 3.1.4 on 2021-01-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210119_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Extra_features',
            field=models.JSONField(default=dict),
        ),
    ]
