# Generated by Django 3.1.4 on 2020-12-24 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envelopes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Number_10', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='#10 (9.5x4.125)')),
                ('Number_10_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='#10 (9.5x4.125) Discounted')),
                ('Nine_By_Twleve', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='9 x 12')),
                ('Nine_By_Twleve_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='9 x 12 Discounted')),
                ('A7', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='A7 (5.25X7.25)')),
                ('A7_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='A7 (5.25X7.25) Discounted')),
            ],
            options={
                'verbose_name': '17 - Envelope',
            },
        ),
        migrations.CreateModel(
            name='LetterHeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Eight_By_Five_By_Eleven', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='8.5" x 11"')),
                ('Eight_By_Five_By_Eleven_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='8.5" x 11" Discounted')),
            ],
            options={
                'verbose_name': '18 - LetterHead',
            },
        ),
        migrations.CreateModel(
            name='NotePads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Three_By_Six_By_Four_By_Eight', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='3.625" x 4.875"')),
                ('Three_By_Six_By_Four_By_Eight_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='3.625" x 4.875" Discounted')),
            ],
            options={
                'verbose_name': '19 - NotePad',
            },
        ),
    ]
