# Generated by Django 3.1.4 on 2020-12-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Stationary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envelopes',
            options={'verbose_name': '1 - Envelope'},
        ),
        migrations.AlterModelOptions(
            name='letterheads',
            options={'verbose_name': '2 - LetterHead'},
        ),
        migrations.AlterModelOptions(
            name='notepads',
            options={'verbose_name': '3 - NotePad'},
        ),
    ]
