# Generated by Django 3.1.4 on 2020-12-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Stationary', '0002_auto_20201224_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelopes',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
        migrations.AddField(
            model_name='letterheads',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
        migrations.AddField(
            model_name='notepads',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
    ]
