# Generated by Django 3.1.4 on 2020-12-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Stationary', '0003_auto_20201224_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelopes',
            name='A7_Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Stationary_Templates'),
        ),
        migrations.AddField(
            model_name='envelopes',
            name='Nine_By_Twelve_Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Stationary_Templates'),
        ),
        migrations.AddField(
            model_name='envelopes',
            name='Number_10_Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Stationary_Templates'),
        ),
        migrations.AddField(
            model_name='letterheads',
            name='Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Business_Stationary_Templates'),
        ),
    ]
