# Generated by Django 3.1.4 on 2020-12-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Stationary', '0004_auto_20201224_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(default='prod', max_length=50)),
                ('Description', models.TextField(default='des', max_length=5000)),
                ('image1', models.ImageField(upload_to='static/Product_Images/Business_Stationary/')),
                ('image2', models.ImageField(upload_to='static/Product_Images/Business_Stationary/')),
                ('image3', models.ImageField(upload_to='static/Product_Images/Business_Stationary/')),
            ],
            options={
                'verbose_name': '0 - Product List',
            },
        ),
        migrations.RemoveField(
            model_name='envelopes',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='letterheads',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='notepads',
            name='Description',
        ),
    ]
