# Generated by Django 3.1.4 on 2021-01-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Stationary', '0007_auto_20210102_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelopes',
            name='A7_Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Stationary_Templates'),
        ),
        migrations.AlterField(
            model_name='envelopes',
            name='Nine_By_Twelve_Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Stationary_Templates'),
        ),
        migrations.AlterField(
            model_name='envelopes',
            name='Number_10_Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Stationary_Templates'),
        ),
        migrations.AlterField(
            model_name='letterheads',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Business_Stationary_Templates'),
        ),
    ]
