# Generated by Django 3.1.4 on 2021-01-21 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Stationary', '0008_auto_20210108_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envelopes',
            old_name='A7_Template',
            new_name='Template',
        ),
        migrations.RemoveField(
            model_name='envelopes',
            name='A7_Discounted',
        ),
        migrations.RemoveField(
            model_name='envelopes',
            name='Nine_By_Twelve_Template',
        ),
        migrations.RemoveField(
            model_name='envelopes',
            name='Nine_By_Twleve_Discounted',
        ),
        migrations.RemoveField(
            model_name='envelopes',
            name='Number_10_Discounted',
        ),
        migrations.RemoveField(
            model_name='envelopes',
            name='Number_10_Template',
        ),
        migrations.RemoveField(
            model_name='letterheads',
            name='Eight_By_Five_By_Eleven_Discounted',
        ),
        migrations.RemoveField(
            model_name='notepads',
            name='Three_By_Six_By_Four_By_Eight_Discounted',
        ),
        migrations.AddField(
            model_name='envelopes',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='letterheads',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='notepads',
            name='Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Discount'),
        ),
    ]
