# Generated by Django 3.1.4 on 2021-01-21 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Stationary', '0009_auto_20210121_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelopes',
            name='A7',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='A7 (5.25X7.25)'),
        ),
        migrations.AlterField(
            model_name='envelopes',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='envelopes',
            name='Nine_By_Twleve',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='9 x 12'),
        ),
        migrations.AlterField(
            model_name='envelopes',
            name='Number_10',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='#10 (9.5x4.125)'),
        ),
        migrations.AlterField(
            model_name='extra_features',
            name='paper_type_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='extra_features',
            name='second_side_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='extra_features',
            name='standard_window_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='letterheads',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='letterheads',
            name='Eight_By_Five_By_Eleven',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='8.5" x 11"'),
        ),
        migrations.AlterField(
            model_name='notepads',
            name='Discounted',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='notepads',
            name='Three_By_Six_By_Four_By_Eight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='3.625" x 4.875"'),
        ),
    ]
