# Generated by Django 3.1 on 2021-02-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business_Stationary', '0010_auto_20210121_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelopes',
            name='Template',
        ),
        migrations.RemoveField(
            model_name='letterheads',
            name='Template',
        ),
        migrations.AddField(
            model_name='envelopes',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='letterheads',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
