# Generated by Django 3.1.4 on 2020-12-24 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorStickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': '26 - Floor Sticker',
            },
        ),
        migrations.CreateModel(
            name='FoamcorePosters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': '20 - Foamcore Poster',
            },
        ),
        migrations.CreateModel(
            name='PosterPrinting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': '21 - Poster Printing',
            },
        ),
        migrations.CreateModel(
            name='RetractableBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity_From', models.PositiveIntegerField(default=0)),
                ('Quantity_To', models.PositiveIntegerField(default=0)),
                ('Thirty_Three_By_Eighty', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='33" x 80"')),
                ('Thirty_Three_By_Eighty_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='33" x 80" Discounted')),
            ],
            options={
                'verbose_name': '22 - Retractable Banner',
            },
        ),
        migrations.CreateModel(
            name='TableCovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity_From', models.PositiveIntegerField(default=0)),
                ('Quantity_To', models.PositiveIntegerField(default=0)),
                ('Ninety_By_One_Three_Two', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='6 foot table cover (90" x 132")')),
                ('Ninety_By_One_Three_Two_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='6 foot table cover (90" x 132") Discounted')),
            ],
            options={
                'verbose_name': '23 - Table Cover',
            },
        ),
        migrations.CreateModel(
            name='QuotationPosterPrinting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dimensionX', models.PositiveIntegerField(default=0)),
                ('dimensionY', models.PositiveIntegerField(default=0)),
                ('PosterPrinting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Large_Format_Printing.posterprinting', verbose_name='Poster Printing')),
            ],
            options={
                'verbose_name': '21.1 - Poster Printing',
            },
        ),
        migrations.CreateModel(
            name='QuotationFoamcorePosters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dimensionX', models.PositiveIntegerField(default=0)),
                ('dimensionY', models.PositiveIntegerField(default=0)),
                ('FoamcorePosters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Large_Format_Printing.foamcoreposters', verbose_name='Foamcore Posters')),
            ],
            options={
                'verbose_name': '20.1 - Foamcore Poster',
            },
        ),
        migrations.CreateModel(
            name='QuotationFloorStickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dimensionX', models.PositiveIntegerField(default=0)),
                ('dimensionY', models.PositiveIntegerField(default=0)),
                ('FloorStickers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Large_Format_Printing.floorstickers', verbose_name='Floor Stickers')),
            ],
            options={
                'verbose_name': '26.1 - Floor Sticker',
            },
        ),
    ]
