# Generated by Django 3.1.4 on 2020-12-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Large_Format_Printing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorstickers',
            options={'verbose_name': '5 - Floor Sticker'},
        ),
        migrations.AlterModelOptions(
            name='foamcoreposters',
            options={'verbose_name': '1 - Foamcore Poster'},
        ),
        migrations.AlterModelOptions(
            name='posterprinting',
            options={'verbose_name': '2 - Poster Printing'},
        ),
        migrations.AlterModelOptions(
            name='quotationfloorstickers',
            options={'verbose_name': '5.1 - Floor Sticker'},
        ),
        migrations.AlterModelOptions(
            name='quotationfoamcoreposters',
            options={'verbose_name': '1.1 - Foamcore Poster'},
        ),
        migrations.AlterModelOptions(
            name='quotationposterprinting',
            options={'verbose_name': '2.1 - Poster Printing'},
        ),
        migrations.AlterModelOptions(
            name='retractablebanners',
            options={'verbose_name': '3 - Retractable Banner'},
        ),
        migrations.AlterModelOptions(
            name='tablecovers',
            options={'verbose_name': '4 - Table Cover'},
        ),
    ]
