# Generated by Django 3.1.4 on 2020-12-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Large_Format_Printing', '0002_auto_20201224_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorstickers',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
        migrations.AddField(
            model_name='foamcoreposters',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
        migrations.AddField(
            model_name='posterprinting',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
        migrations.AddField(
            model_name='retractablebanners',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
        migrations.AddField(
            model_name='tablecovers',
            name='Description',
            field=models.TextField(default='des', max_length=2048),
        ),
    ]
