# Generated by Django 3.1.4 on 2020-12-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Large_Format_Printing', '0003_auto_20201224_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='retractablebanners',
            name='Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Large_Format_Printing_Templates'),
        ),
    ]
