# Generated by Django 3.1.4 on 2020-12-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Large_Format_Printing', '0004_retractablebanners_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(default='prod', max_length=50)),
                ('Description', models.TextField(default='des', max_length=5000)),
                ('image1', models.ImageField(upload_to='static/Product_Images/Large_Format_Printing/')),
                ('image2', models.ImageField(upload_to='static/Product_Images/Large_Format_Printing/')),
                ('image3', models.ImageField(upload_to='static/Product_Images/Large_Format_Printing/')),
            ],
            options={
                'verbose_name': '0 - Product List',
            },
        ),
        migrations.RemoveField(
            model_name='floorstickers',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='foamcoreposters',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='posterprinting',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='retractablebanners',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='tablecovers',
            name='Description',
        ),
    ]
