# Generated by Django 3.1.4 on 2021-01-02 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Large_Format_Printing', '0005_auto_20201225_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_material', models.CharField(blank=True, max_length=250)),
                ('banner_material_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('second_side_printing_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '0 - Extra Features',
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product List'},
        ),
    ]
