# Generated by Django 3.1.4 on 2021-01-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Large_Format_Printing', '0007_auto_20210102_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retractablebanners',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Large_Format_Printing_Templates'),
        ),
    ]
