# Generated by Django 3.1.4 on 2021-01-09 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Large_Format_Printing', '0008_auto_20210108_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foamcoreposters',
            name='quantity',
        ),
        migrations.AddField(
            model_name='foamcoreposters',
            name='Discount',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='foamcoreposters',
            name='Eighteen_By_TwentyFour',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='18" x 24" per Unit Cost'),
        ),
        migrations.AddField(
            model_name='foamcoreposters',
            name='FourtySix_By_FourtyEight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='46" x 48" per Unit Cost'),
        ),
        migrations.AddField(
            model_name='foamcoreposters',
            name='Quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='foamcoreposters',
            name='ThirtySix_By_FourtyEight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='36" x 48" per Unit Cost'),
        ),
        migrations.AddField(
            model_name='foamcoreposters',
            name='Twelve_By_Eighteen',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='12" x 18" per Unit Cost'),
        ),
        migrations.AddField(
            model_name='foamcoreposters',
            name='TwentyFour_By_ThirtySix',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='24" x 36" per Unit Cost'),
        ),
        migrations.AddField(
            model_name='foamcoreposters',
            name='TwentyFour_By_TwentyFour',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='24" x 24" per Unit Cost'),
        ),
        migrations.AddField(
            model_name='foamcoreposters',
            name='Twenty_By_Thrity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='20" x 30" per Unit Cost'),
        ),
        migrations.DeleteModel(
            name='QuotationFoamcorePosters',
        ),
    ]
