# Generated by Django 3.1.4 on 2021-01-21 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Large_Format_Printing', '0010_auto_20210110_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationposterprinting',
            name='PosterPrinting',
        ),
        migrations.RenameField(
            model_name='floorstickers',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='retractablebanners',
            old_name='Thirty_Three_By_Eighty_Discounted',
            new_name='Discount',
        ),
        migrations.RemoveField(
            model_name='posterprinting',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='tablecovers',
            name='Ninety_By_One_Three_Two_Discounted',
        ),
        migrations.AddField(
            model_name='floorstickers',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='floorstickers',
            name='Eighteen',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='18" Circle Cost'),
        ),
        migrations.AddField(
            model_name='floorstickers',
            name='Eighteen_By_TwentyFour',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='18" x 24" Rectangle Cost'),
        ),
        migrations.AddField(
            model_name='floorstickers',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Large_Format_Printing_Templates'),
        ),
        migrations.AddField(
            model_name='floorstickers',
            name='ThirtySix_By_FourtyEight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='36" x 48" Rectangle Cost'),
        ),
        migrations.AddField(
            model_name='floorstickers',
            name='Twelve_By_Twelve',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='12" x 12" Square Cost'),
        ),
        migrations.AddField(
            model_name='floorstickers',
            name='TwentyFour_By_TwentyFour',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='24" x 24" Square Cost'),
        ),
        migrations.AddField(
            model_name='posterprinting',
            name='Discount',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='posterprinting',
            name='Eighteen_By_TwentyFour',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='18" x 24" Cost'),
        ),
        migrations.AddField(
            model_name='posterprinting',
            name='FourtyEight_By_FourtyEight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='48" x 48" Cost'),
        ),
        migrations.AddField(
            model_name='posterprinting',
            name='Quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='posterprinting',
            name='SeventyTwo_By_TwentyFour',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='72" x 24" Cost'),
        ),
        migrations.AddField(
            model_name='posterprinting',
            name='ThirtySix_By_FourtyEight',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='36" x 48" Cost'),
        ),
        migrations.AddField(
            model_name='posterprinting',
            name='TwentyFour_By_ThirtySix',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='24" x 36" Cost'),
        ),
        migrations.AddField(
            model_name='posterprinting',
            name='TwentySeven_By_Forty',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='27" x 40" Cost'),
        ),
        migrations.AddField(
            model_name='posterprinting',
            name='Twenty_By_Thrity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='20" x 30" Cost'),
        ),
        migrations.AddField(
            model_name='tablecovers',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Discount'),
        ),
        migrations.DeleteModel(
            name='QuotationFloorStickers',
        ),
        migrations.DeleteModel(
            name='QuotationPosterPrinting',
        ),
    ]
