# Generated by Django 3.1.4 on 2021-01-21 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Large_Format_Printing', '0011_auto_20210121_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_features',
            name='banner_material_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='extra_features',
            name='second_side_printing_price',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='floorstickers',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='retractablebanners',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='33" x 80" Discounted'),
        ),
        migrations.AlterField(
            model_name='retractablebanners',
            name='Thirty_Three_By_Eighty',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='33" x 80"'),
        ),
        migrations.AlterField(
            model_name='tablecovers',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='tablecovers',
            name='Ninety_By_One_Three_Two',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='6 foot table cover (90" x 132")'),
        ),
    ]
