# Generated by Django 3.1 on 2021-02-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Large_Format_Printing', '0012_auto_20210121_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retractablebanners',
            old_name='Quantity_From',
            new_name='Quantity',
        ),
        migrations.RemoveField(
            model_name='retractablebanners',
            name='Quantity_To',
        ),
    ]
