# Generated by Django 3.1 on 2021-02-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Large_Format_Printing', '0013_auto_20210203_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablecovers',
            old_name='Quantity_From',
            new_name='Quantity',
        ),
        migrations.RemoveField(
            model_name='tablecovers',
            name='Quantity_To',
        ),
    ]
