# Generated by Django 3.1 on 2021-02-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Large_Format_Printing', '0014_auto_20210203_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorstickers',
            name='Template',
        ),
        migrations.RemoveField(
            model_name='retractablebanners',
            name='Template',
        ),
        migrations.AddField(
            model_name='floorstickers',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='retractablebanners',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
