# Generated by Django 3.1.4 on 2020-12-24 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrochuresAndFlyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '9 - Brochures and Flyer',
            },
        ),
        migrations.CreateModel(
            name='Calendars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'verbose_name': '8 - Calendar',
            },
        ),
        migrations.CreateModel(
            name='CustomHolidayCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Folding_Card', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Folding card - closed size is 5" x 7"')),
                ('Folding_Card_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Folding card - closed size is 5" x 7" Discounted')),
            ],
            options={
                'verbose_name': '16 - Custom Holiday Card',
            },
        ),
        migrations.CreateModel(
            name='DirectMailPostCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': '11 - Direct Mail PostCard',
            },
        ),
        migrations.CreateModel(
            name='HangTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Three_By_Five_By_One_By_Five', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='3.5" x 1.5"')),
                ('Three_By_Five_By_One_By_Five_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='3.5" x 1.5" Discounted')),
                ('Two_By_Five_By_Two_By_Five', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='2.5" x 2.5"')),
                ('Two_By_Five_By_Two_By_Five_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='2.5" x 2.5" Discounted')),
                ('Two_By_Six', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='2" x 6"')),
                ('Two_By_Six_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='2" x 6" Discounted')),
            ],
            options={
                'verbose_name': '12 - Hang Tag',
            },
        ),
        migrations.CreateModel(
            name='LabelsAndStickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Two_By_Two', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='2" x 2"')),
                ('Two_By_Two_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='2" x 2" Discounted')),
                ('Three_By_Three', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='3" x 3"')),
                ('Three_By_Three_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='3" x 3" Discounted')),
                ('Four_By_Four', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='4" x 4"')),
                ('Four_by_Four_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='4" x 4" Discounted')),
            ],
            options={
                'verbose_name': '13 - Labels And Sticker',
            },
        ),
        migrations.CreateModel(
            name='NCRForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Five_By_Five_By_Eight_By_Five', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='5.5" x 8.5"')),
                ('Five_By_Five_By_Eight_By_Five_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='5.5" x 8.5" Discounted')),
                ('Eight_By_Five_By_Eleven', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='8.5" x 11"')),
                ('Eight_By_Five_By_Eleven_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='8.5" x 11" Discounted')),
            ],
            options={
                'verbose_name': '14 - NCR Form',
            },
        ),
        migrations.CreateModel(
            name='PostCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '10 - Post Card',
            },
        ),
        migrations.CreateModel(
            name='PresentationFolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('Nine_By_Twelve_Fast', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='9" x 12" Fast - Digital Fast')),
                ('Nine_By_Twelve_Fast_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='9" x 12" Digital Fast Discounted')),
                ('Nine_By_Twelve_Offset', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='9" x 12" Offset Folders')),
                ('Nine_By_Twelve_Offset_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='9" x 12" Offset Discounted')),
            ],
            options={
                'verbose_name': '15 - Presentation Folder',
            },
        ),
        migrations.CreateModel(
            name='QuotationPostCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dimensionX', models.PositiveIntegerField(default=0)),
                ('dimensionY', models.PositiveIntegerField(default=0)),
                ('PostCards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostCards', to='Marketing_Products.postcards')),
            ],
            options={
                'verbose_name': '10.1 - Quotation Post Card',
            },
        ),
        migrations.CreateModel(
            name='QuotationDirectMailPostCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_Discounted', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('dimensionX', models.PositiveIntegerField(default=0)),
                ('dimensionY', models.PositiveIntegerField(default=0)),
                ('DirectMailPostCards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DirectMailPostCards', to='Marketing_Products.postcards')),
            ],
            options={
                'verbose_name': '11.1 - Direct Mail PostCard',
            },
        ),
    ]
