# Generated by Django 3.1.4 on 2020-12-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brochuresandflyers',
            options={'verbose_name': '2 - Brochures and Flyer'},
        ),
        migrations.AlterModelOptions(
            name='calendars',
            options={'verbose_name': '1 - Calendar'},
        ),
        migrations.AlterModelOptions(
            name='customholidaycards',
            options={'verbose_name': '9 - Custom Holiday Card'},
        ),
        migrations.AlterModelOptions(
            name='directmailpostcards',
            options={'verbose_name': '4 - Direct Mail PostCard'},
        ),
        migrations.AlterModelOptions(
            name='hangtags',
            options={'verbose_name': '5 - Hang Tag'},
        ),
        migrations.AlterModelOptions(
            name='labelsandstickers',
            options={'verbose_name': '6 - Labels And Sticker'},
        ),
        migrations.AlterModelOptions(
            name='ncrforms',
            options={'verbose_name': '7 - NCR Form'},
        ),
        migrations.AlterModelOptions(
            name='postcards',
            options={'verbose_name': '3 - Post Card'},
        ),
        migrations.AlterModelOptions(
            name='presentationfolders',
            options={'verbose_name': '8 - Presentation Folder'},
        ),
        migrations.AlterModelOptions(
            name='quotationdirectmailpostcards',
            options={'verbose_name': '4.1 - Direct Mail PostCard'},
        ),
        migrations.AlterModelOptions(
            name='quotationpostcards',
            options={'verbose_name': '3.1 - Quotation Post Card'},
        ),
    ]
