# Generated by Django 3.1.4 on 2020-12-24 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0002_auto_20201224_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationpostcards',
            name='templates',
            field=models.FileField(default=datetime.datetime(2020, 12, 24, 15, 38, 24, 706204, tzinfo=utc), upload_to='static/'),
            preserve_default=False,
        ),
    ]
