# Generated by Django 3.1.4 on 2020-12-24 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0004_auto_20201224_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationpostcards',
            name='templates',
        ),
        migrations.AddField(
            model_name='templates',
            name='card',
            field=models.CharField(choices=[('PostCards/', 'PostCards'), ('QuotationPostCards/', 'QuotationPostCards'), ('BrochuresAndFlyers/', 'BrochuresAndFlyers'), ('DirectMailPostCards/', 'DirectMailPostCards'), ('QuotationDirectMailPostCards/', 'QuotationDirectMailPostCards'), ('Calendars/', 'Calendars'), ('HangTags/', 'HangTags'), ('LabelsAndStickers/', 'LabelsAndStickers'), ('NCRForms/', 'NCRForms'), ('PresentationFolders/', 'PresentationFolders'), ('CustomHolidayCards/', 'CustomHolidayCards')], default=datetime.datetime(2020, 12, 24, 16, 8, 31, 187317, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='templates',
            name='file',
            field=models.FileField(upload_to='static/<django.db.models.fields.CharField>'),
        ),
    ]
