# Generated by Django 3.1.4 on 2020-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0005_auto_20201224_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='file',
            field=models.FileField(max_length=256, upload_to='static/<django.db.models.fields.CharField>'),
        ),
    ]
