# Generated by Django 3.1.4 on 2020-12-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0008_auto_20201224_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='file',
            field=models.FileField(max_length=256, upload_to='static/%cards/'),
        ),
    ]
