# Generated by Django 3.1.4 on 2020-12-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0012_auto_20201224_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Templates',
        ),
        migrations.AddField(
            model_name='calendars',
            name='Description',
            field=models.TextField(default='des', max_length=1024),
        ),
    ]
