# Generated by Django 3.1.4 on 2020-12-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0014_auto_20201224_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='customholidaycards',
            name='Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Marketing_Products_Templates'),
        ),
        migrations.AddField(
            model_name='presentationfolders',
            name='Nine_By_Twelve_Offset_Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Marketing_Products_Templates'),
        ),
        migrations.AddField(
            model_name='presentationfolders',
            name='Nine_by_Twleve_Fast_Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Marketing_Products_Templates'),
        ),
        migrations.AddField(
            model_name='quotationdirectmailpostcards',
            name='Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Marketing_Products_Templates'),
        ),
        migrations.AddField(
            model_name='quotationpostcards',
            name='Template',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Marketing_Products_Templates'),
        ),
    ]
