# Generated by Django 3.1.4 on 2020-12-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0015_auto_20201224_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendars',
            name='label',
            field=models.CharField(default='Calender', editable=False, max_length=30),
        ),
    ]
