# Generated by Django 3.1.4 on 2020-12-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0016_calendars_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendars',
            name='image',
            field=models.ImageField(blank=True, max_length=256, upload_to='static/Calender'),
        ),
    ]
