# Generated by Django 3.1.4 on 2020-12-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0017_calendars_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(default='prod', max_length=50)),
                ('Description', models.TextField(default='des', max_length=5000)),
                ('image1', models.ImageField(upload_to='static/Product_Images/Marketing_Products/')),
                ('image2', models.ImageField(upload_to='static/Product_Images/Marketing_Products/')),
                ('image3', models.ImageField(upload_to='static/Product_Images/Marketing_Products/')),
            ],
            options={
                'verbose_name': '0 - Product List',
            },
        ),
        migrations.RemoveField(
            model_name='brochuresandflyers',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='calendars',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='customholidaycards',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='directmailpostcards',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='hangtags',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='labelsandstickers',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='ncrforms',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='postcards',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='presentationfolders',
            name='Description',
        ),
    ]
