# Generated by Django 3.1.4 on 2021-01-02 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0018_auto_20201225_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_side_printing_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('flat_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('half_fold_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('tri_fold_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('z_fold_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('double_parallel_fold_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('individual_cut_labels_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('three_part_form_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('form_numbering_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('paper_type', models.CharField(blank=True, max_length=250)),
                ('paper_type_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('blank_envelope_price', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': '0 - Extra Features',
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product List'},
        ),
    ]
