# Generated by Django 3.1.4 on 2021-01-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0020_auto_20210102_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendars',
            name='image',
        ),
        migrations.AlterField(
            model_name='customholidaycards',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Marketing_Products_Templates'),
        ),
        migrations.AlterField(
            model_name='presentationfolders',
            name='Nine_By_Twelve_Offset_Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Marketing_Products_Templates'),
        ),
        migrations.AlterField(
            model_name='presentationfolders',
            name='Nine_by_Twleve_Fast_Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Marketing_Products_Templates'),
        ),
        migrations.AlterField(
            model_name='quotationdirectmailpostcards',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Marketing_Products_Templates'),
        ),
        migrations.AlterField(
            model_name='quotationpostcards',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Marketing_Products_Templates'),
        ),
    ]
