# Generated by Django 3.1.4 on 2021-01-21 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0021_auto_20210108_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DirectMailPostCards',
        ),
        migrations.RemoveField(
            model_name='quotationpostcards',
            name='PostCards',
        ),
        migrations.RenameField(
            model_name='customholidaycards',
            old_name='Folding_Card_Discounted',
            new_name='Discount',
        ),
        migrations.RenameField(
            model_name='postcards',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='presentationfolders',
            old_name='Nine_By_Twelve_Offset_Template',
            new_name='Template',
        ),
        migrations.RemoveField(
            model_name='brochuresandflyers',
            name='price_Discounted',
        ),
        migrations.RemoveField(
            model_name='calendars',
            name='label',
        ),
        migrations.RemoveField(
            model_name='calendars',
            name='price_Discounted',
        ),
        migrations.RemoveField(
            model_name='hangtags',
            name='Three_By_Five_By_One_By_Five_Discounted',
        ),
        migrations.RemoveField(
            model_name='hangtags',
            name='Two_By_Five_By_Two_By_Five_Discounted',
        ),
        migrations.RemoveField(
            model_name='hangtags',
            name='Two_By_Six_Discounted',
        ),
        migrations.RemoveField(
            model_name='labelsandstickers',
            name='Four_by_Four_Discounted',
        ),
        migrations.RemoveField(
            model_name='labelsandstickers',
            name='Three_By_Three_Discounted',
        ),
        migrations.RemoveField(
            model_name='labelsandstickers',
            name='Two_By_Two_Discounted',
        ),
        migrations.RemoveField(
            model_name='ncrforms',
            name='Eight_By_Five_By_Eleven_Discounted',
        ),
        migrations.RemoveField(
            model_name='ncrforms',
            name='Five_By_Five_By_Eight_By_Five_Discounted',
        ),
        migrations.RemoveField(
            model_name='presentationfolders',
            name='Nine_By_Twelve_Fast_Discounted',
        ),
        migrations.RemoveField(
            model_name='presentationfolders',
            name='Nine_By_Twelve_Offset_Discounted',
        ),
        migrations.RemoveField(
            model_name='presentationfolders',
            name='Nine_by_Twleve_Fast_Template',
        ),
        migrations.AddField(
            model_name='brochuresandflyers',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='calendars',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='hangtags',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='labelsandstickers',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='ncrforms',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Discount',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Eight_By_Five',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='8" x 5" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Eight_By_Five_By_Eleven',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='8.5" x 11" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Eight_By_Five_By_Five_By_Five',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='8.5" x 5.5" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Eight_By_Five_By_Three_By_Five',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='8.5" x 3.5" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Five_By_Five',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='5" x 5" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Five_By_Seven',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='5" x 7" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Four_By_Five',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='4" x 5" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Four_By_Five_By_Twelve',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='4.5" x 12" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Four_By_Four',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='4" x 4" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Four_By_Nine',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='4" x 9" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Four_By_Six',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='4" x 6" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Four_By_Twelve',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='4" x 12" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Four_By_TwoFive_By_Eleven',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='4.25" x 11" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Four_By_TwoFive_By_FiveByFive',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='4.25" x 5.5" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Four_By_TwoFive_By_Nine',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='4.25" x 9" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Four_By_TwoFive_By_Six',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='4.25" x 6" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Six_By_Eleven',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='6" x 11" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Six_By_Five_By_Eleven',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='6.5" x 9" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Six_By_Nine',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='6" x 9" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Six_By_Six',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='6" x 6" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Six_By_TwoFive_By_Eleven',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='6.25" x 11" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Six_By_TwoFive_By_Nine',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='6.25" x 9" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Template',
            field=models.FileField(blank=True, max_length=256, upload_to='static/Marketing_Products_Templates'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Three_By_Five',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='3" x 5" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Three_By_Five_By_Five',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='3.5" x 5" Cost'),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Two_By_Eight',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='2" x 8" Cost'),
        ),
        migrations.AddField(
            model_name='presentationfolders',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='brochuresandflyers',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='calendars',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.DeleteModel(
            name='QuotationDirectMailPostCards',
        ),
        migrations.DeleteModel(
            name='QuotationPostCards',
        ),
    ]
