# Generated by Django 3.1.4 on 2021-01-21 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0022_auto_20210121_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customholidaycards',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Folding card - closed size is 5" x 7" Discounted'),
        ),
        migrations.AlterField(
            model_name='customholidaycards',
            name='Folding_Card',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Folding card - closed size is 5" x 7"'),
        ),
        migrations.AlterField(
            model_name='hangtags',
            name='Three_By_Five_By_One_By_Five',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='3.5" x 1.5"'),
        ),
        migrations.AlterField(
            model_name='hangtags',
            name='Two_By_Five_By_Two_By_Five',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='2.5" x 2.5"'),
        ),
        migrations.AlterField(
            model_name='hangtags',
            name='Two_By_Six',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='2" x 6"'),
        ),
        migrations.AlterField(
            model_name='labelsandstickers',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='labelsandstickers',
            name='Four_By_Four',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='4" x 4"'),
        ),
        migrations.AlterField(
            model_name='labelsandstickers',
            name='Three_By_Three',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='3" x 3"'),
        ),
        migrations.AlterField(
            model_name='labelsandstickers',
            name='Two_By_Two',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='2" x 2"'),
        ),
        migrations.AlterField(
            model_name='ncrforms',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='ncrforms',
            name='Eight_By_Five_By_Eleven',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='8.5" x 11"'),
        ),
        migrations.AlterField(
            model_name='ncrforms',
            name='Five_By_Five_By_Eight_By_Five',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='5.5" x 8.5"'),
        ),
        migrations.AlterField(
            model_name='presentationfolders',
            name='Discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='presentationfolders',
            name='Nine_By_Twelve_Fast',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='9" x 12" Fast - Digital Fast'),
        ),
        migrations.AlterField(
            model_name='presentationfolders',
            name='Nine_By_Twelve_Offset',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='9" x 12" Offset Folders'),
        ),
    ]
