# Generated by Django 3.1 on 2021-02-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_Products', '0023_auto_20210121_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customholidaycards',
            name='Template',
        ),
        migrations.RemoveField(
            model_name='postcards',
            name='Template',
        ),
        migrations.RemoveField(
            model_name='presentationfolders',
            name='Template',
        ),
        migrations.AddField(
            model_name='customholidaycards',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='postcards',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='presentationfolders',
            name='Template1',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
